# Generated by Django 6.0.6 on 2026-06-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
